name: ryde_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/core/constants/assets

flutter:
  uses-material-design: true
  assets:
    - assets/images/
